name: Android CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: tagv${{ github.run_number }}
        release_name: Release${{ github.run_number }}
        body: |
            ${{ steps.Changelog.outputs.changelog }}
        draft: false
        prerelease: false
    - name: upload release asset
      id: upload-release-asset2
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./app/build/outputs/apk/release/app-release.apk
        asset_name: CCTV_Viewer_v${{ github.run_number }}.apk
        asset_content_type: application/zip  
